### ISSUE TITLE
avax.xml.bind.PropertyException: name: eclipselink.media-type value: application/xml 	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.setProperty(AbstractUnmarshallerImpl.java:352)

### ISSUE THREAD

**Issue by jasontrublu** [WolfgangFahl/Mediawiki-Japi#23]
Hi,

I've got an exception while fetching a page from de.wikipedia.org. The content is received but apparently not parseable.  Building Mediawiki-Japi with tests fails as well, but with different errors.

Test code:
   @Test
    public void testSampleQuery() throws Exception {
        Mediawiki wiki = new Mediawiki("http://en.wikipedia.org");
        String content = wiki.getPageContent("Main Page");
        assertTrue(content.contains("Wikipedia"));
    }

exception:

/usr/lib/jvm/java-7-openjdk-amd64/bin/java -ea -Didea.launcher.port=7532 -Didea.launcher.bin.path=/home/trublu/bin/idea/bin -Dfile.encoding=UTF-8 -classpath /home/trublu/bin/idea/lib/idea_rt.jar:/home/trublu/bin/idea/plugins/junit/lib/junit-rt.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rhino.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/compilefontconfig.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/management-agent.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/javazic.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/icedtea-sound.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/java-atk-wrapper.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/sunpkcs11.jar:/home/trublu/git/hipedia/bot1/target/test-classes:/home/trublu/git/hipedia/bot1/target/classes:/home/trublu/.m2/repository/com/bitplan/mediawiki-japi/0.0.11/mediawiki-japi-0.0.11.jar:/home/trublu/.m2/repository/com/google/inject/guice/3.0/guice-3.0.jar:/home/trublu/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/home/trublu/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/home/trublu/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/home/trublu/.m2/repository/com/sun/jersey/jersey-client/1.18/jersey-client-1.18.jar:/home/trublu/.m2/repository/com/sun/jersey/jersey-core/1.18/jersey-core-1.18.jar:/home/trublu/.m2/repository/com/sun/jersey/contribs/jersey-apache-client/1.18/jersey-apache-client-1.18.jar:/home/trublu/.m2/repository/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar:/home/trublu/.m2/repository/commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.jar:/home/trublu/.m2/repository/commons-codec/commons-codec/1.2/commons-codec-1.2.jar:/home/trublu/.m2/repository/com/sun/jersey/contribs/jersey-multipart/1.18/jersey-multipart-1.18.jar:/home/trublu/.m2/repository/org/jvnet/mimepull/mimepull/1.9.3/mimepull-1.9.3.jar:/home/trublu/.m2/repository/org/eclipse/persistence/org.eclipse.persistence.moxy/2.6.0-M3/org.eclipse.persistence.moxy-2.6.0-M3.jar:/home/trublu/.m2/repository/org/eclipse/persistence/org.eclipse.persistence.core/2.6.0-M3/org.eclipse.persistence.core-2.6.0-M3.jar:/home/trublu/.m2/repository/org/eclipse/persistence/org.eclipse.persistence.asm/2.6.0-M3/org.eclipse.persistence.asm-2.6.0-M3.jar:/home/trublu/.m2/repository/org/eclipse/persistence/org.eclipse.persistence.antlr/2.6.0-M3/org.eclipse.persistence.antlr-2.6.0-M3.jar:/home/trublu/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar:/home/trublu/.m2/repository/args4j/args4j/2.0.29/args4j-2.0.29.jar:/home/trublu/.m2/repository/org/slf4j/slf4j-api/1.5.6/slf4j-api-1.5.6.jar:/home/trublu/.m2/repository/org/slf4j/slf4j-jdk14/1.5.6/slf4j-jdk14-1.5.6.jar:/home/trublu/.m2/repository/junit/junit/4.11/junit-4.11.jar:/home/trublu/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 LibrarieTest,testSampleQuery
Nov 20, 2015 4:05:15 PM com.bitplan.mediawiki.japi.api.Api fromXML
SEVERE: name: eclipselink.media-type value: application/xml
Nov 20, 2015 4:05:15 PM com.bitplan.mediawiki.japi.api.Api fromXML
INFO: <?xml version="1.0"?><api batchcomplete=""><query><pages><page _idx="15580374" pageid="15580374" ns="0" title="Main Page"><revisions><rev contentformat="text/x-wiki" contentmodel="wikitext" xml:space="preserve">&lt;!--        BANNER ACROSS TOP OF PAGE        --&gt;
{| id=&quot;mp-topbanner&quot; style=&quot;width:100%; background:#f9f9f9; margin:1.2em 0 6px 0; border:1px solid #ddd;&quot;
| style=&quot;width:61%; color:#000;&quot; |
&lt;!--        &quot;WELCOME TO WIKIPEDIA&quot; AND ARTICLE COUNT        --&gt;
{| style=&quot;width:280px; border:none; background:none;&quot;
| style=&quot;width:280px; text-align:center; white-space:nowrap; color:#000;&quot; |
&lt;div style=&quot;font-size:162%; border:none; margin:0; padding:.1em; color:#000;&quot;&gt;Welcome to [[Wikipedia]],&lt;/div&gt;
&lt;div style=&quot;top:+0.2em; font-size:95%;&quot;&gt;the [[free content|free]] [[encyclopedia]] that [[Wikipedia:Introduction|anyone can edit]].&lt;/div&gt;
&lt;div id=&quot;articlecount&quot; style=&quot;font-size:85%;&quot;&gt;[[Special:Statistics|{{NUMBEROFARTICLES}}]] articles in [[English language|English]]&lt;/div&gt;
|}
&lt;!--        PORTAL LIST ON RIGHT-HAND SIDE        --&gt;
| style=&quot;width:13%; font-size:95%;&quot; |
* [[Portal:Arts|Arts]]
* [[Portal:Biography|Biography]]
* [[Portal:Geography|Geography]]
| style=&quot;width:13%; font-size:95%;&quot; |
* [[Portal:History|History]]
* [[Portal:Mathematics|Mathematics]]
* [[Portal:Science|Science]]
| style=&quot;width:13%; font-size:95%;&quot; |
* [[Portal:Society|Society]]
* [[Portal:Technology|Technology]]
* '''[[Portal:Contents/Portals|All portals]]'''
|}
&lt;!--        MAIN PAGE BANNER        --&gt;
{{#if:{{Main Page banner}}|
&lt;table id=&quot;mp-banner&quot; style=&quot;width: 100%; margin:4px 0 0 0; background:none; border-spacing: 0px;&quot;&gt;
&lt;tr&gt;&lt;td class=&quot;MainPageBG&quot; style=&quot;padding:8px; background-color:#fffaf5; border:1px solid #f2e0ce; color:#000; font-size:100%;&quot;&gt;{{Main Page banner}}
&lt;/td&gt;&lt;/tr&gt;
&lt;/table&gt;
}}
&lt;!--        TODAY'S FEATURED CONTENT        --&gt;
{| id=&quot;mp-upper&quot; style=&quot;width: 100%; margin:4px 0 0 0; background:none; border-spacing: 0px;&quot;
&lt;!--        TODAY'S FEATURED ARTICLE; DID YOU KNOW        --&gt;
| class=&quot;MainPageBG&quot; style=&quot;width:55%; border:1px solid #cef2e0; background:#f5fffa; vertical-align:top; color:#000;&quot; |
{| id=&quot;mp-left&quot; style=&quot;width:100%; vertical-align:top; background:#f5fffa;&quot;
| style=&quot;padding:2px;&quot; | &lt;h2 id=&quot;mp-tfa-h2&quot; style=&quot;margin:3px; background:#cef2e0; font-family:inherit; font-size:120%; font-weight:bold; border:1px solid #a3bfb1; text-align:left; color:#000; padding:0.2em 0.4em;&quot;&gt;{{#ifexpr:{{formatnum:{{PAGESIZE:Wikipedia:Today's featured article/{{#time:F j, Y}}}}|R}}&gt;150|From today's featured article|Featured article &lt;span style=&quot;font-size:85%; font-weight:normal;&quot;&gt;(Check back later for today's.)&lt;/span&gt;}}&lt;/h2&gt;
|-
| style=&quot;color:#000;&quot; | &lt;div id=&quot;mp-tfa&quot; style=&quot;padding:2px 5px&quot;&gt;{{#ifexpr:{{formatnum:{{PAGESIZE:Wikipedia:Today's featured article/{{#time:F j, Y}}}}|R}}&gt;150|{{Wikipedia:Today's featured article/{{#time:F j, Y}}}}|{{Wikipedia:Today's featured article/{{#time:F j, Y|-1 day}}}}}}&lt;/div&gt;
|-
| style=&quot;padding:2px;&quot; | &lt;h2 id=&quot;mp-dyk-h2&quot; style=&quot;margin:3px; background:#cef2e0; font-family:inherit; font-size:120%; font-weight:bold; border:1px solid #a3bfb1; text-align:left; color:#000; padding:0.2em 0.4em;&quot;&gt;Did you know...&lt;/h2&gt;
|-
| style=&quot;color:#000; padding:2px 5px 5px;&quot; | &lt;div id=&quot;mp-dyk&quot;&gt;{{Did you know}}&lt;/div&gt;
|}
| style=&quot;border:1px solid transparent;&quot; |
&lt;!--        IN THE NEWS; ON THIS DAY        --&gt;
| class=&quot;MainPageBG&quot; style=&quot;width:45%; border:1px solid #cedff2; background:#f5faff; vertical-align:top;&quot;|
{| id=&quot;mp-right&quot; style=&quot;width:100%; vertical-align:top; background:#f5faff;&quot;
| style=&quot;padding:2px;&quot; | &lt;h2 id=&quot;mp-itn-h2&quot; style=&quot;margin:3px; background:#cedff2; font-family:inherit; font-size:120%; font-weight:bold; border:1px solid #a3b0bf; text-align:left; color:#000; padding:0.2em 0.4em;&quot;&gt;In the news&lt;/h2&gt;
|-
| style=&quot;color:#000; padding:2px 5px;&quot; | &lt;div id=&quot;mp-itn&quot;&gt;{{In the news}}&lt;/div&gt;
|-
| style=&quot;padding:2px;&quot; | &lt;h2 id=&quot;mp-otd-h2&quot; style=&quot;margin:3px; background:#cedff2; font-family:inherit; font-size:120%; font-weight:bold; border:1px solid #a3b0bf; text-align:left; color:#000; padding:0.2em 0.4em;&quot;&gt;On this day...&lt;/h2&gt;
|-
| style=&quot;color:#000; padding:2px 5px 5px;&quot; | &lt;div id=&quot;mp-otd&quot;&gt;{{Wikipedia:Selected anniversaries/{{#time:F j}}}}&lt;/div&gt;
|}
|}
&lt;!--        TODAY'S FEATURED LIST        --&gt;&lt;!-- CONDITIONAL SHOW --&gt;{{#switch:{{CURRENTDAYNAME}}|Monday|Friday=
&lt;table id=&quot;mp-middle&quot; style=&quot;width:100%; margin:4px 0 0 0; background:none; border-spacing: 0px;&quot;&gt;
&lt;tr&gt;
&lt;td class=&quot;MainPageBG&quot; style=&quot;width:100%; border:1px solid #f2cedd; background:#fff5fa; vertical-align:top; color:#000;&quot;&gt;
&lt;table id=&quot;mp-center&quot; style=&quot;width:100%; vertical-align:top; background:#fff5fa; color:#000;&quot;&gt;
&lt;tr&gt;
&lt;td style=&quot;padding:2px;&quot;&gt;&lt;h2 id=&quot;mp-tfl-h2&quot; style=&quot;margin:3px; background:#f2cedd; font-family:inherit; font-size:120%; font-weight:bold; border:1px solid #bfa3af; text-align:left; color:#000; padding:0.2em 0.4em&quot;&gt;From today's featured list&lt;/h2&gt;&lt;/td&gt;
&lt;/tr&gt;&lt;tr&gt;
&lt;td style=&quot;color:#000;&quot;&gt;&lt;div id=&quot;mp-tfl&quot; style=&quot;padding:2px 5px;&quot;&gt;{{#ifexist:Wikipedia:Today's featured list/{{#time:F j, Y}}|{{Wikipedia:Today's featured list/{{#time:F j, Y}}}}|{{TFLempty}}}}&lt;/div&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;/table&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/table&gt;|}}&lt;!-- END CONDITIONAL SHOW --&gt;
&lt;!--        TODAY'S FEATURED PICTURE        --&gt;
{| id=&quot;mp-lower&quot; style=&quot;margin:4px 0 0 0; width:100%; background:none; border-spacing: 0px;&quot;
| class=&quot;MainPageBG&quot; style=&quot;width:100%; border:1px solid #ddcef2; background:#faf5ff; vertical-align:top; color:#000;&quot; |
{| id=&quot;mp-bottom&quot; style=&quot;width:100%; vertical-align:top; background:#faf5ff; color:#000;&quot;
| style=&quot;padding:2px;&quot; | &lt;h2 id=&quot;mp-tfp-h2&quot; style=&quot;margin:3px; background:#ddcef2; font-family:inherit; font-size:120%; font-weight:bold; border:1px solid #afa3bf; text-align:left; color:#000; padding:0.2em 0.4em&quot;&gt;{{#ifexist:Template:POTD protected/{{#time:Y-m-d}}|Today's featured picture | Featured picture&amp;ensp;&lt;span style=&quot;font-size:85%; font-weight:normal;&quot;&gt;(Check back later for today's.)&lt;/span&gt;}}&lt;/h2&gt;
|-
| style=&quot;color:#000; padding:2px;&quot; | &lt;div id=&quot;mp-tfp&quot;&gt;{{#ifexist:Template:POTD protected/{{#time:Y-m-d}}|{{POTD protected/{{#time:Y-m-d}}}}|{{POTD protected/{{#time:Y-m-d|-1 day}}}}}}&lt;/div&gt;
|}
|}
&lt;!--        SECTIONS AT BOTTOM OF PAGE        --&gt;
&lt;div id=&quot;mp-other&quot; style=&quot;padding-top:4px; padding-bottom:2px;&quot;&gt;
== Other areas of Wikipedia ==
{{Other areas of Wikipedia}}
&lt;/div&gt;&lt;div id=&quot;mp-sister&quot;&gt;
== Wikipedia's sister projects ==
{{Wikipedia's sister projects}}
&lt;/div&gt;&lt;div id=&quot;mp-lang&quot;&gt;
== Wikipedia languages ==
{{Wikipedia languages}}
&lt;/div&gt;
&lt;!--        INTERWIKI STRAPLINE        --&gt;
&lt;noinclude&gt;{{Main Page interwikis}}{{noexternallanglinks}}{{#if:{{Wikipedia:Main_Page/Tomorrow}}||}}&lt;/noinclude&gt;__NOTOC____NOEDITSECTION__</rev></revisions></page></pages></query></api>

javax.xml.bind.PropertyException: name: eclipselink.media-type value: application/xml
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.setProperty(AbstractUnmarshallerImpl.java:352)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.setProperty(UnmarshallerImpl.java:450)
	at com.bitplan.mediawiki.japi.jaxb.JaxbFactory.fromXML(JaxbFactory.java:120)
	at com.bitplan.mediawiki.japi.api.Api.fromXML(Api.java:300)
	at com.bitplan.mediawiki.japi.MediaWikiApiImpl.fromXML(MediaWikiApiImpl.java:134)
	at com.bitplan.mediawiki.japi.Mediawiki.getActionResult(Mediawiki.java:404)
	at com.bitplan.mediawiki.japi.Mediawiki.getQueryResult(Mediawiki.java:429)
	at com.bitplan.mediawiki.japi.Mediawiki.getPageContent(Mediawiki.java:532)
	at com.bitplan.mediawiki.japi.Mediawiki.getPageContent(Mediawiki.java:560)
	at LibrarieTest.testSampleQuery(LibrarieTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Process finished with exit code 255

**Comment by WolfgangFahl** [comment]
Thank you for the issue report. 

I have add your testCase as TestIssue23 and it runs o.k. in the development environment. Please check again with 0.12 and that testcase on its own.

> Building Mediawiki-Japi with tests fails as well, but with different errors.
At this point the tests run against some Mediawikis that you'd need credentials for. Please contact me by e-mail if you want go get access. 

For the Exception itself: There may be something wrong in the classpath setup. 

See http://stackoverflow.com/questions/20962053/exception-in-thread-main-javax-xml-bind-propertyexception-name-eclipselink-m

If you try mvn dependency:tree you should see the proper EclipseLink jar to be used. 
```
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building BITPlan-Mediawiki-Japi 0.0.12
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ mediawiki-japi ---
[INFO] com.bitplan:mediawiki-japi:jar:0.0.12
[INFO] +- com.google.inject:guice:jar:3.0:compile
[INFO] |  +- javax.inject:javax.inject:jar:1:compile
[INFO] |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] +- commons-io:commons-io:jar:2.4:compile
[INFO] +- com.sun.jersey:jersey-client:jar:1.18:compile
[INFO] |  \- com.sun.jersey:jersey-core:jar:1.18:compile
[INFO] +- com.sun.jersey.contribs:jersey-apache-client:jar:1.18:compile
[INFO] |  \- commons-httpclient:commons-httpclient:jar:3.1:compile
[INFO] |     +- commons-logging:commons-logging:jar:1.0.4:compile
[INFO] |     \- commons-codec:commons-codec:jar:1.2:compile
[INFO] +- com.sun.jersey.contribs:jersey-multipart:jar:1.18:compile
[INFO] |  \- org.jvnet.mimepull:mimepull:jar:1.9.3:compile
[INFO] +- org.eclipse.persistence:org.eclipse.persistence.moxy:jar:2.6.0-M3:compile
[INFO] |  +- org.eclipse.persistence:org.eclipse.persistence.core:jar:2.6.0-M3:compile
[INFO] |  |  \- org.eclipse.persistence:org.eclipse.persistence.asm:jar:2.6.0-M3:compile
[INFO] |  \- org.eclipse.persistence:org.eclipse.persistence.antlr:jar:2.6.0-M3:compile
[INFO] +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] +- com.sun.jersey.contribs:jersey-moxy:jar:1.18:provided
[INFO] +- junit:junit:jar:4.11:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- args4j:args4j:jar:2.0.29:compile
[INFO] \- org.mockito:mockito-core:jar:1.10.16:test
[INFO]    \- org.objenesis:objenesis:jar:2.1:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.771 s
[INFO] Finished at: 2016-01-09T15:34:34+01:00
[INFO] Final Memory: 18M/228M
[INFO] ------------------------------------------------------------------------
```

**Comment by WolfgangFahl** [comment]
The jaxb.properties file is not being picked up by the maven environment. I'v put a redundant copy of it in the test folder and add the main/resources and main/test folders to make the command line run of maven happy.
