### ISSUE TITLE
Problem accessing wiki

### ISSUE THREAD

**Issue by aimdev** [WolfgangFahl/Mediawiki-Japi#26]
Hi

not sure why it fails to find the api on my debian based mediawiki version 1.2.6.2.
to get it to work I had to do this
public static final String DEFAULT_SCRIPTPATH = "";
Now its working so far.

**Comment by WolfgangFahl** [comment]
Thanks for the comment. Having this in the issuelist might be helpful for people having the same problem. I have added a line to http://mediawiki-japi.bitplan.com/mediawiki-japi/index.php/Examples#API_usage_examples to point this out
