### ISSUE TITLE
How can I change the DEFAULT_SCRIPTPATH?

### ISSUE THREAD

**Issue by TobiMayr** [WolfgangFahl/Mediawiki-Japi#28]
My mediawiki installation has the api at mywiki.com/api.php and not mywiki.com/w/api.php.

How can I change this since I imported the JAPI as a Maven Dependency?

Thank you very much!

**Comment by WolfgangFahl** [comment]
Thank you for using Mediawki-Japi

```
void setScriptPath(String scriptPath)

set the scriptPath of this Wiki

Parameters:
    scriptPath - - the scriptPath to set
```
See the API Doc at http://wolfgangfahl.github.io/Mediawiki-Japi/apidocs/index.html
