### ISSUE TITLE
Ability to automatically run tests for CI builds

### ISSUE THREAD

**Issue by intracer** [WolfgangFahl/Mediawiki-Japi#35]
Now some tests are failing and require  configuration

Failed tests: 
  TestAPI_Edit.testDelete:90 expected:<0> but was:<3>
  TestAPI_Login.testGetUser:38 User credentials not found/configured
  TestAPI_Login.testLogin:72 Need to be able to read Credentials for 
        http://mediawiki-japi.bitplan.com
from /home/ilya/.mediawiki-japi/ilya_mediawiki-japi-test1_19.ini
Please run 
        java -cp target/test-classes com.bitplan.mediawiki.japi.user.WikiUser mediawiki-japi-test1_19
to create it. Then restart your tests.
  TestAPI_Login.testLoginWrongPassword:96 Need to be able to read Credentials for 
        http://mediawiki-japi.bitplan.com
from /home/ilya/.mediawiki-japi/ilya_mediawiki-japi-test1_19.ini
Please run 
        java -cp target/test-classes com.bitplan.mediawiki.japi.user.WikiUser mediawiki-japi-test1_19
to create it. Then restart your tests.
Tests in error: 
  TestAPI_Allpages.testAllImages:51 » NullPointer
  TestAPI_Allpages.testAllpages:38 » NullPointer
  TestAPI_Allpages.testBacklink:81 » NullPointer
  TestAPI_Allpages.testImagesInfosForPage:115 » NullPointer
  TestAPI_Allpages.testImagesOnPage:92 » NullPointer
  TestAPI_Edit.TestEdit:104 » NullPointer
  TestAPI_Edit.TestURLengthLimit:126 » NullPointer
  TestAPI_Edit.testCopy:167 » NullPointer
  TestAPI_Edit.testEditNoLogin:150 » NullPointer
  TestAPI_Edit.testEditSection:211 » NullPointer
  TestAPI_Edit.testGetEditToken:56 » NullPointer
  TestAPI_Login.testLoginToken:53 NullPointer
  TestAPI_Recentchanges.testGetMostRecentChanges:96 » NullPointer
  TestAPI_Upload.testUpload:36 » NullPointer
  TestAPI_Upload.testUploadViaII:60 » NullPointer
  TestCreateAccount.testCreateAccount:40 » NullPointer
  TestProtectionMarker.testProtectionMarker:26 » NullPointer

Tests run: 74, Failures: 4, Errors: 17, Skipped: 0

**Comment by WolfgangFahl** [comment]
Any suggestions welcome see http://mediawiki-japi.bitplan.com/mediawiki-japi/index.php/Developer_Info#Credentials_for_the_test_example_Mediawikis

**Comment by WolfgangFahl** [comment]
The tests are now disable if no credentials are available. The Warning shows only once. If you'd like to get credentials for the test wikis just let me know and I'll supply them for you. You can add with the procedure outlined:

`java -cp target/classes com.bitplan.mediawiki.japi.user.WikiUser mediawiki-japi-test1_19
`

All parameters can now also be given via the commandline to automate the process of creating files with the encrypted credentials.
