### ISSUE TITLE
Javadoc link leads to 404

### ISSUE THREAD

**Issue by ahstro** [WolfgangFahl/Mediawiki-Japi#40]
[The Javadoc link](http://wolfgangfahl.github.io/Mediawiki-Japi/apidocs/index.html) leads to a 404. Looking at the commits in the `gh-pages`-branch, the latest commit - 4f3009e2ef326adf6332d2712b1ee0bad55b9627 - seems to be the culprit. Not sure if intentional or not?

**Comment by WolfgangFahl** [comment]
It's a bug see https://stackoverflow.com/questions/51915991/check-of-pom-xml-to-be-compliant-with-mvn-site-command-for-github-pages - i am in the process of fixing it.
